# Generated by Django 4.1 on 2024-05-06 04:08

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("profile", models.CharField(max_length=50)),
                ("description", ckeditor.fields.RichTextField()),
                ("photo", models.ImageField(upload_to="media/slider/%Y/")),
                ("github_url", models.CharField(max_length=550)),
                ("linkedin_url", models.CharField(max_length=550)),
                ("user_mail", models.CharField(max_length=550)),
                ("experience", models.IntegerField()),
                ("education", models.CharField(max_length=255)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
