# Generated by Django 4.1 on 2024-05-07 18:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0002_alter_userdetail_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
