# Generated by Django 4.1 on 2024-05-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0003_alter_userdetail_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology", models.CharField(max_length=255)),
                (
                    "exprience",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("experienced", "Experienced"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_soft", models.CharField(max_length=255)),
                (
                    "tool_exprience",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("experienced", "Experienced"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
