# Generated by Django 4.1 on 2024-05-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0004_techstack_toolstack"),
    ]

    operations = [
        migrations.RenameField(
            model_name="techstack", old_name="exprience", new_name="experience",
        ),
        migrations.RenameField(
            model_name="toolstack",
            old_name="tool_exprience",
            new_name="tool_experience",
        ),
    ]
