# Generated by Django 4.1 on 2024-05-08 00:29

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0005_rename_exprience_techstack_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proj_name", models.CharField(max_length=50)),
                ("github_link", models.CharField(max_length=50)),
                (
                    "proj_link",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("photo", models.ImageField(upload_to="media/slider/%Y/")),
            ],
        ),
    ]
