# Generated by Django 4.1 on 2024-05-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0006_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="proj_link",
            field=models.CharField(max_length=50),
        ),
    ]
